events {}

http {
    server {
        listen 80;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        location /static/ {
            alias /var/www/backend_static/;
        }

        location /media/ {
            alias /var/www/backend_media/;
        }

        location /api/ {
            proxy_pass http://backend:8000;
        }

        location /admin/ {
            proxy_pass http://backend:8000;
        }
    }
}
